language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  postgresql: "9.6"

services:
  - mysql

php:
  - 7.2

env:
  - DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE

matrix:
  include:
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - phpenv config-rm xdebug.ini
  - cd ../..
  - nvm install node;
  - nvm install 14.0.0;
  - nvm use 14.0.0;
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
#  - php moodle/local/datacleaner/tests/privacy/privacy.php
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
